### ISSUE TITLE
Question about rendered depth map of StereoMIS dataset

### ISSUE THREAD

**Issue by neneyork** [jinlab-imvr/Deform3DGS#5]
Hi, thanks for your work in transforming StereoMIS dataset into EndoNeRF formate. But I find that the rendered depth map of StereoMIS significantly differs from the ground truth. Could you please explain why would this occurs? Thank you!

**Comment by lala-sean** [comment]
Hi, sorry for missing the comment. The depth l1 loss on StereoMIS is slightly worse than EndoNeRF dataset. I suspect this is due to the relatively more complex motions of StereoMIS clips and the erroneous prediction of depth using RAFT. Could you share how large the depth errors can be? since we didn't observe a quantitatively significant difference in depth errors between the two datasets.
